votacao.settings:
  type: config_object
  label: 'Configurações da Votação'
  mapping:
    api_token:
      type: string
      label: 'Token da API'
    disable:
      type: boolean
      label: 'Desativar sistema de votação'
