<?php

/**
 * @file
 * Primary module hooks for Votação module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function votacao_theme(): array {
  return [
    'vtc_pergunta' => ['render element' => 'elements'],
    'votacao_form' => [
      'variables' => [
        'pergunta' => NULL,
        'opcoes' => [],
      ],
      'template' => 'votacao-form',
    ],
  ];
}

/**
 * Prepares variables for pergunta templates.
 *
 * Default template: vtc-pergunta.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the pergunta information and
 *   any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_vtc_pergunta(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function votacao_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish perguntas.
      $storage = Drupal::entityTypeManager()->getStorage('vtc_pergunta');
      $vtc_pergunta_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($vtc_pergunta_ids) as $vtc_pergunta) {
        $vtc_pergunta->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize perguntas.
      $storage = Drupal::entityTypeManager()->getStorage('vtc_pergunta');
      $vtc_pergunta_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($vtc_pergunta_ids) as $vtc_pergunta) {
        $vtc_pergunta->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function votacao_user_predelete(UserInterface $account): void {
  // Delete perguntas that belong to this account.
  $storage = Drupal::entityTypeManager()->getStorage('vtc_pergunta');
  $vtc_pergunta_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($vtc_pergunta_ids)
  );
  // Delete old revisions.
  $vtc_pergunta_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  foreach (array_keys($vtc_pergunta_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}
