<?php

/**
 * @file
 * Primary module hooks for Votação module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function votacao_theme(): array {
  return [
    'votacao_form' => [
      'variables' => [
        'pergunta' => NULL,
        'opcoes' => [],
        'show_results' => NULL,
      ],
      'template' => 'votacao-form',
    ],
  ];
}
